const repoList = [
  {
    type: 'Public',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projetos_react_js',
    repoDescription: 'Projetos desenvolvidos apenas com a biblioteca ReactJS, a partir de layouts e aplicações disponíveis na web.',
    license: 'MIT license',
    lang: 'JavaScript',
  },
  {
    type: 'Private',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projeto_private_exemplo2',
    repoDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sapien nibh, semper ac justo ut, eleifend aliquam.',
    lang: 'CSS',
  },
  {
    type: 'Public',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projetos_javascript',
    repoDescription: 'Projetos desenvolvidos apenas com JavaScript Puro, a partir de layouts e aplicações disponíveis na web.',
    license: 'MIT license',
    lang: 'HTML',
  },
  {
    type: 'Public',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projetos_html_e_sass',
    repoDescription: 'Projetos desenvolvidos somente com HTML e o poderoso pré-processador SASS, a partir de layouts e aplicações disponíveis na web.',
    license: 'MIT license',
    lang: 'Sass',
  },
  {
    type: 'Public',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projetos_html_e_css',
    repoDescription: 'Projetos desenvolvidos apenas com HTML e CSS, a partir de layouts e aplicações disponíveis na web.',
    license: 'MIT license',
    lang: 'HTML',
  },
  {
    type: 'Private',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projeto_private_exemplo1',
    repoDescription: 'Morbi at est nec enim scelerisque condimentum ut sit amet felis. Aliquam maximus leo at ex congue laoreet. Praesent hendrerit diam ut tellus pulvinar hendrerit.',
    lang: 'CSS',
  },
  {
    type: 'Public',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projetos_curso_js_b7web',
    repoDescription: 'Projetos desenvolvidos durante o curso de JavaScript da B7Web sob tutela do professor, Bonieky Lacerda.',
    license: 'MIT license',
    lang: 'JavaScript',
  },
  {
    type: 'Public',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projetos_curso_sass_udemy',
    repoDescription: 'Os projetos contidos neste repositório foram desenvolvidos durante o curso de SASS e SCSS do professor Matheus Battisti na Udemy.',
    license: 'MIT license',
    lang: 'HTML',
  },
  {
    type: 'Private',
    typeDefault: 'All',
    langDefault: 'All',
    repoTitle: 'projeto_private_exemplo3',
    repoDescription: 'Nullam vel orci lacinia, pellentesque tortor ac, ullamcorper risus. Phasellus vitae lacus sit amet nulla finibus facilisis.',
    lang: 'JavaScript',
  },
];

export default repoList;